# ============================================
# LISTE DES SERVEURS
# ============================================

[webservers]
# Remplacez l'IP par celle de votre serveur
# (cf. terraform output -raw instance_public_ip)
ec2-api ansible_host=3.90.215.127

[webservers:vars]
# Comment se connecter
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/tp-api-keypair
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ConnectTimeout=15'
ansible_ssh_timeout=20